### ISSUE TITLE
Adding GiveItem to ExtendedRCON

### ISSUE THREAD

**Issue by KevinCollmer** [Michidu/Ark-Server-Plugins#1]
Hey,

could you add GiveItem <steamID> <Blueprint Path> <Count> <Quality> <BP>

It would make alot of things easier :)

**Comment by KevinCollmer** [comment]
`void GiveItem(RCONClientConnection* rconClientConnection, RCONPacket* rconPacket, UWorld* uWorld)
{
	FString msg = rconPacket->Body;

	TArray<FString> Parsed;
	msg.ParseIntoArray(&Parsed, L" ", true);

	if (Parsed.IsValidIndex(5))
	{
		unsigned __int64 steamId;
		FString* blueprintPath;
		int quantity;
		float quality;
		bool forceBP;

		try
		{
			steamId = std::stoull(*Parsed[1]);
			blueprintPath = &Parsed[2];
			quantity = std::stoi(*Parsed[3]);
			quality = std::stof(*Parsed[4]);
			forceBP = std::stoi(*Parsed[5]) != 0;
		}
		catch (const std::exception&)
		{
			return;
		}

		AShooterPlayerController* aShooterPC = FindPlayerControllerFromSteamId(steamId);
		if (aShooterPC)
		{
			aShooterPC->GiveItem(blueprintPath, quantity, quality, forceBP);

			// Send a reply
			FString reply = L"Successfully gave items\n";
			rconClientConnection->SendMessageW(rconPacket->Id, 0, &reply);
		}
	}
}`

this doesnt work - server is crashing.

**Comment by Michidu** [comment]
It was added.
