### ISSUE TITLE
not restart Groups invalid ?

### ISSUE THREAD

**Issue by cokll** [Michidu/Ark-Server-Plugins#13]
set TimedPointsReward group

 "Groups": {
                "Default": {
                    "Amount": 10
                }, 
                "VIP1": {
                    "Amount": 100
                }, 
                "VIP2": {
                    "Amount": 1000
                }, 
                "VIP3": {
                    "Amount": 10000
                }

**Comment by Michidu** [comment]
It looks fine, what exactly your problem is?

**Comment by cokll** [comment]
How do not restart the entry into force
