### ISSUE TITLE
[ExtendedRCON] - ScriptCommand Overload

### ISSUE THREAD

**Issue by Reginherus** [Michidu/Ark-Server-Plugins#17]
Fantastic work with this!

Is there any possible way to write an overload method to mitigate script commands that are not associated with a player(SteamID)? Or is it how WC designed the script command?

This is a side question, but relevant. I saw your post in the Modding Forums that you can use script commands via RCON natively without the use of Extended RCON. Is this still the case?

**Comment by Michidu** [comment]
It always should be associated with a player, because only players can run it as far as i know.
I don't remember that i wrote it somewhere, don't think you can.
