### ISSUE TITLE
Project configuration isn't flexible

### ISSUE THREAD

**Issue by InRedikaWB** [Michidu/Ark-Server-Plugins#18]
I was trying to build plugin and got a lot of error. I think, we need to add some description to project.
1. Add requirements. You mention that VS17 is needed, but project also use Win10 SDK 16299.
2. For compiling plugin ark-server-api is necessary.  Using git submodule seems like a good solution. Or just mention in readme that you need to clone other repo.
3. In .vcxproj config VS store information about path to other projects and libs. Probably, config from repo will only work for you. I waste some time to configure it. Readme is needed to add some information about how to reset this path for each computer.
4. There isn't no .gitignore file, is it? I compile plugin and git said tht i had created 32 files.

**Comment by InRedikaWB** [comment]
Pull request for second task: #19

**Comment by InRedikaWB** [comment]
Pull request for fourth task: #20

**Comment by Michidu** [comment]
They can be compiled with multiple SDK versions however.
I guess you will still need to change the paths. But i will add it to the readme.
And thanks for the pull requests.
