### ISSUE TITLE
SteamId duplicates

### ISSUE THREAD

**Issue by Krucifixionador** [Michidu/Ark-Server-Plugins#23]
It is very common that when you assign the same DB to several servers, they end up with duplicate SteamId. It would be great if it could be managed from mysql just like the "Permissions" plugin, it would surely solve the problem, besides facilitating the interaction of the mods with a website.

**Comment by Krucifixionador** [comment]
I forgot to mention, of course I'm talking about the Ark Shop.

**Comment by Michidu** [comment]
It's planned. However, duplicate steam ids shouldn't happen because it checks before adding.

**Comment by Krucifixionador** [comment]
Of 4000 ids it has been able to duplicate me 5, but it is also a problem.

**Comment by Michidu** [comment]
With mysql it shouldn't be a problem
