### ISSUE TITLE
VS 2017 compile

### ISSUE THREAD

**Issue by criticalplus** [Michidu/Ark-Server-Plugins#3]
Hi, first thanks for the project, we are trying to translate the plugin from the store. We have a problem compiling it, I get many errors. I copied the API files into the project, any advice? Thank you

` C: \ users \ rx \ source \ repos \ ark-plugin \ arkshop \ arkshop \ api \ ue.h (257): error C3646: 'Rotation': unknown invalidation specifier
(257): error C4430: The type specifier is missing; c: \ users \ rx \ source \ repos \ ark-plugin \ arkshop \ arkshop \ api \ Is presupposed int. NOTE: C ++ does not support default-int
(258): error C3646: 'Translation': Invalidation specifier unknown (1): c: \ users \ rx \ source \ repos \ ark-plugin \ arkshop \ arkshop \ api \ ue.h
(258): error C4430: The type specifier is missing; c: \ users \ rx \ source \ repos \ ark-plugin \ arkshop \ arkshop \ api \ Is presupposed int. NOTE: C ++ does not support default-int
(259): error C3646: 'Scale3D': Unknown Invalidator Specifier (C: \ Program Files \
(259): Error C4430: The type specifier is missing; c: \ users \ rx \ source \ repos \ ark-plugin \ arkshop \ arkshop \ api \ Is presupposed int. NOTE: C ++ does not support default-int
1> TimedRewards.cpp`

**Comment by Michidu** [comment]
Did you include the latest version of "API" folder (from ArkApi)? Did you also include ArkApi.lib?

**Comment by criticalplus** [comment]
Hello, good morning, thank you very much for taking the time to respond, we are very grateful. I have not programmed for a long time and I'm somewhat rusty ... lol

What I did was install the GitHub repositories plugin and download the project to my hard drive. Try to compile it and skip API errors.

What I did was to copy the API folder inside ArkShop so I managed to change the errors I mentioned in the first message. I leave you a photo of where I placed the API folder.
`https://fotos.subefotos.com/08a4ec3a0ccd1106e4385d7d8866039do.gif`

I think the problem may be ArkApi.lib?

Thank you again for your time and dedication. A greeting.

**Comment by Michidu** [comment]
It looks correct, just use api from there https://github.com/Michidu/ARK-Server-Beyond-API/tree/master/ArkApi/API
You will need ArkApi.lib too.

**Comment by criticalplus** [comment]
I have the API files added and the entry "#pragma comment (lib," ArkApi.lib ")" in "ArkShop.cpp". 
I do not know where he's failing. We just want to translate the plugin shop. Maybe some VisualStudio configuration? Thanks
`https://fotos.subefotos.com/fa748deabec772f1b79d59b74c4c30c0o.gif`

**Comment by Michidu** [comment]
It works fine with VS 2017. Are you compiling it in Release(x64) mode?

**Comment by criticalplus** [comment]
ActiveDebug x64 configuration
It looks like the .lib file you told me. Where exactly do I download it? In the repository link I do not see it. Thanks ^^
`
1>    Variables de entorno pasadas a la herramienta:
1>      VS_UNICODE_OUTPUT=884
1>    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\bin\HostX86\x64\link.exe /ERRORREPORT:PROMPT /OUT:"C:\Users\rx\Source\Repos\ark-Plugin\ArkShop\x64\Debug\ArkShop.dll" /INCREMENTAL /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG:FASTLINK /PDB:"C:\Users\rx\Source\Repos\ark-Plugin\ArkShop\x64\Debug\ArkShop.pdb" /SUBSYSTEM:WINDOWS /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:\Users\rx\Source\Repos\ark-Plugin\ArkShop\x64\Debug\ArkShop.lib" /MACHINE:X64 /DLL x64\Debug\ArkShop.obj
1>    x64\Debug\DBHelper.obj
1>    x64\Debug\Kits.obj
1>    x64\Debug\Market.obj
1>    x64\Debug\Points.obj
1>    x64\Debug\Store.obj
1>    x64\Debug\ShopAPI.obj
1>    x64\Debug\sqlite3.obj
1>    x64\Debug\TimedRewards.obj
1>    x64\Debug\Tools.obj
1>    Comando de seguimiento:
1>    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Tracker.exe /a /d "C:\Program Files (x86)\MSBuild\15.0\FileTracker\FileTracker32.dll" /i C:\Users\rx\Source\Repos\ark-Plugin\ArkShop\ArkShop\x64\Debug\ArkShop.tlog /r "C:\USERS\RX\SOURCE\REPOS\ARK-PLUGIN\ARKSHOP\ARKSHOP\X64\DEBUG\ARKSHOP.OBJ|C:\USERS\RX\SOURCE\REPOS\ARK-PLUGIN\ARKSHOP\ARKSHOP\X64\DEBUG\DBHELPER.OBJ|C:\USERS\RX\SOURCE\REPOS\ARK-PLUGIN\ARKSHOP\ARKSHOP\X64\DEBUG\KITS.OBJ|C:\USERS\RX\SOURCE\REPOS\ARK-PLUGIN\ARKSHOP\ARKSHOP\X64\DEBUG\MARKET.OBJ|C:\USERS\RX\SOURCE\REPOS\ARK-PLUGIN\ARKSHOP\ARKSHOP\X64\DEBUG\POINTS.OBJ|C:\USERS\RX\SOURCE\REPOS\ARK-PLUGIN\ARKSHOP\ARKSHOP\X64\DEBUG\SHOPAPI.OBJ|C:\USERS\RX\SOURCE\REPOS\ARK-PLUGIN\ARKSHOP\ARKSHOP\X64\DEBUG\SQLITE3.OBJ|C:\USERS\RX\SOURCE\REPOS\ARK-PLUGIN\ARKSHOP\ARKSHOP\X64\DEBUG\STORE.OBJ|C:\USERS\RX\SOURCE\REPOS\ARK-PLUGIN\ARKSHOP\ARKSHOP\X64\DEBUG\TIMEDREWARDS.OBJ|C:\USERS\RX\SOURCE\REPOS\ARK-PLUGIN\ARKSHOP\ARKSHOP\X64\DEBUG\TOOLS.OBJ" /b MSBuildConsole_CancelEventb994f58301634fb3a6eeefe0a98fa73c  /c "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\bin\HostX86\x64\link.exe"  /ERRORREPORT:PROMPT /OUT:"C:\Users\rx\Source\Repos\ark-Plugin\ArkShop\x64\Debug\ArkShop.dll" /INCREMENTAL /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG:FASTLINK /PDB:"C:\Users\rx\Source\Repos\ark-Plugin\ArkShop\x64\Debug\ArkShop.pdb" /SUBSYSTEM:WINDOWS /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:\Users\rx\Source\Repos\ark-Plugin\ArkShop\x64\Debug\ArkShop.lib" /MACHINE:X64 /DLL x64\Debug\ArkShop.obj
1>    x64\Debug\DBHelper.obj
1>    x64\Debug\Kits.obj
1>    x64\Debug\Market.obj
1>    x64\Debug\Points.obj
1>    x64\Debug\Store.obj
1>    x64\Debug\ShopAPI.obj
1>    x64\Debug\sqlite3.obj
1>    x64\Debug\TimedRewards.obj
1>    x64\Debug\Tools.obj
**1>    LINK : fatal error LNK1104: no se puede abrir el archivo 'ArkApi.lib'**
1>    El comando salió con el código 1104.
1>  Ejecución de la tarea "Link" terminada -- ERROR.
1>Compilación terminada del destino "Link" en el proyecto "ArkShop.vcxproj" -- ERROR.
1>
1>Compilación del proyecto "ArkShop.vcxproj" terminada -- ERROR.
1>
1>ERROR al compilar.
1>
1>Tiempo transcurrido 00:00:29.24
========== Recompilar todo: 0 correctos, 1 incorrectos, 0 omitidos ==========`

**Comment by Michidu** [comment]
The one from download archive should work. Just make you link it correctly in VS
 (you need to specify folder, https://msdn.microsoft.com/en-us/library/ee855621.aspx). Also, it's better to compile in Release mode.

**Comment by criticalplus** [comment]
Thank you very much, it seems that I understand the problem. I think I've added the library well, now it tells me that 'kernel32.lib' is missing.

https://fotos.subefotos.com/54f5d6860b3dd987122785bfbcad15b6o.gif

I've tried it with the default libraries + ArkApi.obj; But returns the LINK error: fatal error LNK1104: can not open file 'ArkApi.lib'
https://fotos.subefotos.com/307383ad3386a5c3e3c4543134bca7c3o.gif

thanks for your time

**Comment by Michidu** [comment]
Don't remove default libraries. And you need to specify the folder where ArkApi.lib is located, not the file itself.

**Comment by criticalplus** [comment]
I have tried several routes without success, a capture of your route as an example would help me a lot. I do not want to waste your time with something so simple, sorry. And thank you very much
```
$(VC_LibraryPath_x64);$(WindowsSDK_LibraryPath_x64);$(NETFXKitsDir)Lib\um\x64;C:\Users\rx\Source\Repos\ARK-Server-Beyond-API2\ArkApi\x64\Debug
$(VC_LibraryPath_x64);$(WindowsSDK_LibraryPath_x64);$(NETFXKitsDir)Lib\um\x64;C:\Users\rx\Source\Repos\ARK-Server-Beyond-API2\ArkApi\x64\Debug\$(LibraryPath);
```

**Comment by criticalplus** [comment]
At last I have managed to compile it, now it is necessary to prove that I have not broken anything with the translation. Jejeje

Thank you very much for your time, you have really been very helpful to me.
