### ISSUE TITLE
/buyKit not working.

### ISSUE THREAD

**Issue by gthgame** [Michidu/Ark-Server-Plugins#5]
There is an issue with /buykit , it's no working here.  the /kit name is working , but when i do /buykit name 1 , i receive only you have successfull bought name kit but the items don't come in my inventory. 

Cordialy,

**Comment by Michidu** [comment]
/buykit only adds kits. It doesn't redeem them.

**Comment by gthgame** [comment]
So there is no way to /buy a kit if 0 avalaible left ? ? what about the Price in kit section ?

**Comment by Michidu** [comment]
After /buykit name X, you need to use /kit name.

**Comment by gthgame** [comment]
Fixed.
