### ISSUE TITLE
version 275

### ISSUE THREAD

**Issue by lemignon** [Michidu/Ark-Server-Plugins#7]
Hello, 

the shop is not working anymore since version 275. timed points works , but /points , /shop ... not working anymore ? 

Cordialy

**Comment by Kev90sc1** [comment]
Not working on my server as well??

**Comment by lemignon** [comment]
yes it's not working at all michidu added bug label 

Michidu any news ? is there a way of fixing beyond api ?

**Comment by urdeadagain** [comment]
also extended rcon is now broken, thanks for the update Michidu on the ark server plugin, if we could get your magic on the other would be awesome

**Comment by Michidu** [comment]
I've updated binaries a few days ago. If you need source code, look at this fork: https://github.com/tsebring/ARK-Server-Beyond-API
Currently, working on v2.0...

**Comment by lemignon** [comment]
ok thank you . don't need update the plugins ? only binaries will solve the problem ?

**Comment by Michidu** [comment]
Yes, you need to update only the api itself.

**Comment by lemignon** [comment]
oh ok thank you :) going to try , good job :D
