### ISSUE TITLE
ArkAPI is not recognizing ArkShop Build

### ISSUE THREAD

**Issue by Natemiller24** [Michidu/Ark-Server-Plugins#9]
I downloaded the ArkAPI DLL package and placed it into the Shootergame/Binaries/Win64 directory, along with the compiled ArkShop.DLL, that I got from GitHub and compiled, inside of Shootergame/binaries/win64/BeyondAPI/Plugins/ArkShop. When I launch the server, it does not load the ArkShop plugin.

For testing, I switched out the ArkShop.dll with the downloadable one from the website and it works fine.

To compile the ArkShop project, I opened the solution -> retargetted project for Windows SDK Version 10.0.16299.0 -> added the API folder, from the ArkAPI source code, into the project directory. I then compiled the ArkAPI to get an ArkAPI.Lib in which I placed into the resources section in visual studios. After that, the solution build and provided me with the ArkShop.DLL that I used above. Am I doing something wrong here?

**Comment by Michidu** [comment]
Does it tried to load it? Do you see any error?

**Comment by Natemiller24** [comment]
The API loads perfectly find and it does try to load the plugins, it just goes from  Dumping Structures..., Dumping functions... to Loaded all plugins, API was successfully loaded. If I place the precompiled ArkShop.dll in the plugins folded I get Dumping Structures..., Dumping functions... ArkShop Plugin
 Loaded all plugins, API was successfully loaded.

**Comment by Michidu** [comment]
It seems like the problem in the file name. Make sure it's named exactly "ArkShop.dll". Anyway, i would suggest you to this version for now https://github.com/tsebring/ARK-Server-Beyond-API.

**Comment by Natemiller24** [comment]
the file name is ArkShop.dll. I've tried to compile with tsebring's version and still run into the same issue. I did notice though that the downloadable ArkShop.dll is 847 KB while mine is 2047KB. Not sure where to go from here. Just trying to get it up and running so I can start making adjustments to learn/attempt to add a sell feature.

**Comment by cokll** [comment]
Missing config.json

**Comment by Natemiller24** [comment]
That was the first thing I checked cause I remembered that if the config.json was incorrect that the plugin would not load correctly. I know that's not the case because when I put in the downloadable dll into the directory, the plugin loads with no problems.
